### ISSUE TITLE
Mysql type BIT(1) should be treated as Boolean

### ISSUE THREAD

**Issue by medzes** [strongloop/loopback-connector-mysql#151]
During discovery, all MySQL BIT types are seens as Binary. But for 1-bit types it makes more sense to see them as Boolean.

**Comment by santhoshscs** [comment]
right now the bit field is coming as 
```
<fieldname>: {
type: "Buffer",
data: [
0
]
},
```
It would be great to treat these bit fields as Boolean

**Comment by shaheero** [comment]
Also TINYINT should be discovered as Boolean. Now it is discovered as Number.
But CHAR (with a length of 1) is being discovered as Boolean.

**Comment by shaheero** [comment]
Another funny thing is that a MySQL type Char (length =1) would always give "true" in the JSON!

**Comment by superkhau** [comment]
I believe this is related to #202. Trying to land that PR ATM.

**Comment by ssh24** [comment]
Should be fixed in this PR https://github.com/strongloop/loopback-connector-mysql/pull/232. Closing this issue. Feel free to reopen if needed.

**Comment by yongzhi-chen** [comment]
still getting <Buffer 01> when it is converting mysql to model property (in this function MySQL.prototype.fromColumnValue)

**Comment by bajtos** [comment]
@yongzhi-chen thank you for the comment. Let's move the discussion to https://github.com/strongloop/loopback-connector-mysql/issues/325 please.
